# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
