# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-30 21:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_communique'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='communique',
            new_name='message',
        ),
    ]
