# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-29 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_level',
            field=models.IntegerField(choices=[(1, 'normal'), (9, 'admin')], default=1),
        ),
    ]
