# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communiques', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communique',
            name='privacy',
            field=models.IntegerField(choices=[(0, 'private'), (1, 'public')], default=1),
        ),
    ]
